#### 4.1.2.4. 배열 형태 변환

In [1]:
import numpy as np

In [5]:
# 1차원 배열 -> 2차원 배열(3행 2열)
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(3, 2)
print(arr)  # arr는 그대로임!

[1 2 3 4 5 6]


In [8]:
# 1차원 -> 3차원 배열
arr = np.arange(24)
print(arr.reshape(2, 3, 4))  # 면 2, 행 3, 열 4
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [37]:
# 2차원 배열 -> 1차원 배열 (복사본 변환)
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.flatten())

f_arr = arr.flatten()
print(arr)
print(f_arr)

arr[0][0] = 10
print(arr)
print(f_arr)      # 원본은 그대로!

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[10  2  3]
 [ 4  5  6]]
[1 2 3 4 5 6]


In [38]:
# 2차원 배열 -> 1차원 배열 (가능하면 뷰 반환)
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.ravel())

r_arr = arr.ravel()
print(arr)
print(r_arr)

arr[0][0] = 10
print(arr)
print(r_arr)    # 얕은 복사가 된 것, 원본 수정됨.

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[10  2  3]
 [ 4  5  6]]
[10  2  3  4  5  6]


In [15]:
# 2차원 배열에서 transpose()
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [29]:
# 3차원 배열에서 transpose()
arr = np.arange(24).reshape(2, 3, 4)

# 축 순서 바꾸기 : (0, 1, 2) -> (1, 0, 2)
# shape : (3, 2, 4)

print(arr)
print(arr.transpose(1, 0, 2))          # 3면 2행 4열로 변환 shape
print(arr.transpose(1, 0, 2).shape)    # (3, 2, 4)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
(3, 2, 4)


In [28]:
# 3차원 배열에서 axis 0과 axis 2 교환
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(np.swapaxes(arr, 0,2))
print(np.swapaxes(arr, 0, 2).shape)

[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]
(2, 2, 2)


#### 4.1.2.6. 배열 복사

In [33]:
# 얕은 복사
arr = np.arange(6)
print(arr)

copy_arr = arr.view()
print(copy_arr)

copy_arr[0] = 10
print(arr)
print(copy_arr)  # 원본도 같이 바뀜

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[10  1  2  3  4  5]
[10  1  2  3  4  5]


In [39]:
# 깊은 복사
arr = np.arange(6)
print(arr)

copy_arr = arr.copy()
print(copy_arr)

copy_arr[0] = 10
print(arr)
print(copy_arr)

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
[10  1  2  3  4  5]


### 4.1.3. 넘파이 배열 인덱싱과 슬라이싱

In [43]:
# 1차원 인덱싱과 슬라이싱

arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[::2])

1
5
[2 3 4]
[1 3 5]


In [46]:
# 인덱싱은 기본적으로 얕은 복사임
arr = np.array([1,2,3,4,5])
value = arr[0]
value = 10
print(arr)
print(value)

arr[0] = 10
print(arr)    # 인덱싱이 얕은복사를 하고 있었기에 인덱스 추가가 가능함

[1 2 3 4 5]
10
[10  2  3  4  5]


In [45]:
# 슬라이싱은 기본적으로 뷰(View)임
arr = np.array([1,2,3,4,5])
print(arr)

sub_arr = arr[1:4]
print(sub_arr)

sub_arr[0] = 100
print(arr)
print(sub_arr)

[1 2 3 4 5]
[2 3 4]
[  1 100   3   4   5]
[100   3   4]


In [47]:
# copy() 함수를 이용해서 깊은 복사를 해야 원본이 변하지 않음
arr = np.array([1,2,3,4,5])
print(arr)

sub_arr = arr[1:4].copy()
print(sub_arr)

sub_arr[0] = 100
print(arr)
print(sub_arr)

[1 2 3 4 5]
[2 3 4]
[1 2 3 4 5]
[100   3   4]


In [57]:
# 2차원 인덱싱과 슬라이싱
arr = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print(arr[0][0])
print(arr[0, 0])
print(arr[0])    # 첫번째 행 가져오라는 의미, 열에 대해서는 지정 안했기에
print(arr[0, :])
print(arr[:, 0]) # 모든 행의 두 번째 열
print(arr[1:, :2]) # 두번째 행부터 끝까지, 처음부터 두번째 열까지

1
1
[1 2 3]
[1 2 3]
[1 4 7]
[[4 5]
 [7 8]]


In [52]:
lst = [[1,2,3],     [4,5,6],    [7,8,9]]
lst[0][0]
print(lst[0, 0])   # 리스트는 이거 안됨!

TypeError: list indices must be integers or slices, not tuple

In [68]:
# 3차원 인덱싱과 슬라이싱
arr = np.arange(24).reshape(2,3,4)

print(arr)
print(arr[0][0][0])
print(arr[0, 0, 0]) # 이렇게도 된다! 리스트는 안됨.

print(arr[1])       # 두 번째 면의 모든 값
print(arr[1][2])   # 두 번째 면의 세번째 행의 모든 값
print(arr[1,2])
print("\n")
print(arr[:, 1, :])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
0
0
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[20 21 22 23]
[20 21 22 23]


[[ 4  5  6  7]
 [16 17 18 19]]


In [72]:
lst = [1, 2, 3, 4, 5]
# print(lst[0], lst[3], lst[4])
lst[[0,3,4]]

TypeError: list indices must be integers or slices, not list

In [74]:
# 팬시 인덱싱  (깊은 연산)
arr = np.array([1,2,3,4,5])
print(arr[[0,3,4]])

[1 4 5]


In [79]:
# 불리언 인덱싱  (깊은 연산)
arr = np.array([1,2,3,4,5])
print(arr > 3)             # bool형 배열
print(arr[arr > 3])

[False False False  True  True]
[4 5]


In [83]:
lst1 = [1,2,3]
lst2 = [10,20,30]

print(lst1 + lst2)

[lst[i]+lst2[i] for i in range(3)]   #[lst1[0] + lst2[0], ...]



[1, 2, 3, 10, 20, 30]


[11, 22, 33]

In [89]:
arr1 = np.array(lst1)
arr2 = np.array(lst2)

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]
[1 2 3]


In [92]:
a = np.array(5).reshape(1,)    # 0차원을 1치원으로!
a.shape
print(a)  

[5]


In [98]:
a = np.arange(3)
print(a.ndim, a.shape)

1 (3,)


In [99]:
a2 = np.arange(3).reshape(1,3)
print(a2.ndim, a2.shape)
print(a2)

2 (1, 3)
[[0 1 2]]


In [100]:
# 브로드캐스팅1 : 1차원 + 스칼라
arr = np.array([1,2,3])
arr + 5  

array([6, 7, 8])

In [104]:
# 브로드캐스팅2 : 차원 수가 다른 경우
arr1 = np.array([[1], [2], [3]])  # shape : (3, 1)
arr2 = np.array([10,20,30,40])    # shape : (4, ) -> (1, 4)로 간주

arr1 + arr2

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43]])

In [107]:
# 브로드캐스팅3: 두 배열의 열의 크기가 다르므로 브로드캐스팅 불가능
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])                 # shape : (2, 3)

arr2 = np.array([10,20,30,40])   # shape : (4,) -> (1, 4)로 간주
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

In [109]:
# 브로드캐스팅: 3차원 + 1차원
arr1 = np.arrange(24).reshape(2, 3, 4)    #          (2, 3, 4)
arr2 = np.array([10, 20, 30, 40])         # (4,)  -> (1, 1, 4)로 간주
arr1 + arr2

AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
# 브로드캐스팅 : 3차원 + 1차원
arr1 = np.arange(24).reshape(2, 3, 4)      # shape : (2, 3, 4)
arr2 = np.array([10, 20, 30, 40])          # shape : (4,) → (1, 1, 4)로 간주

print(arr1.shape, arr2.shape)
print((arr1 + arr2).shape)                 # shaep : (2, 3, 4)
print(arr1 + arr2)