#### 4.1.1.3 넘파이 배열의 속성

In [3]:
import numpy as np

In [4]:
# 넘파이 배열의 속성
[[1, 2, 3], [4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

In [6]:
# 넘파이 배열의 속성
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
print(arr.dtype)

int32


In [10]:
print(arr.ndim)

2


In [11]:
print(arr.shape)

(2, 3)


In [13]:
print(arr.size)

6


In [15]:
# 1byte = 8bit
print(arr.itemsize)

4


### 4.1.2. 차원과 축
#### 4.1.2.1. 차원

In [19]:
arr0 = np.array(3.14)                        # 0차원 배열(스칼라)
arr1 = np.array([3.14])                      # 1차원 배열(벡터)
arr2 = np.array([[3.14]])                    # 2차원 배열(행렬)
arr3 = np.array([[[3.14]]])                  # 3차원 배열(텐서)

print(arr0.ndim, arr0.shape)
print(arr1.ndim, arr1.shape)
print(arr2.ndim, arr2.shape)
print(arr3.ndim, arr3.shape)

0 ()
1 (1,)
2 (1, 1)
3 (1, 1, 1)


In [21]:
# 1차원 배열(벡터)
arr = np.array([1,2,3])
print(arr.ndim, arr.shape)          #튜플이어서 print 안 적어도 되긴 해

1 (3,)


In [23]:
# 2차원 배열(행렬)
arr = np.array([[1,2,3], [4,5,6]])
print(arr.ndim, arr.shape)

2 (2, 3)


In [27]:
# 3차원 배열(텐서)
arr = np.array([[[1,2,3], [4,5,6]], [[11,12,13], [14,15,16]]])
print(arr.ndim, arr.shape)

3 (2, 2, 3)


#### 4.1.2.3. 넘파이 배열 메소드

In [32]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.ndim, arr.shape)
print(np.sum(arr))  # 축 지정 안 했으니 전체에 대해서 적용!
print(np.sum(arr, axis = 0))           #행 방향으로 산출
print(np.sum(arr, axis = 1))           #열 방향으로 산출

2 (2, 3)
21
[5 7 9]
[ 6 15]


In [34]:
# 누적합
print(arr)
print(np.cumsum(arr))
print(np.cumsum(arr, axis = 0))
print(np.cumsum(arr, axis = 1)) 

[[1 2 3]
 [4 5 6]]
[ 1  3  6 10 15 21]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]
