# 3. 자료구조
## 3.5. 딕셔너리
### 3.5.1. 딕셔너리 생성

In [1]:
# 딕셔너리 생성1
dct = {'a': 1, 'b': 2, 'c': 3}
print(dct)

{'a': 1, 'b': 2, 'c': 3}


In [2]:
# 빈 딕셔너리 생성
{}

{}

In [5]:
# 딕셔너리 생성2: 키는 중복될 수 없음
dct = {'a': 1, 'b': 2, 'c': 3, 'a': 3.14, 'a': "Hello"}
print(dct)            # 키는 중복될 수 없으니 a에 가장 마지막에 저장된 값이 저장됨.

{'a': 'Hello', 'b': 2, 'c': 3}


In [6]:
# 딕셔너리 생성3
dct = dict(a=1, b=2, c=3)
print(dct)

{'a': 1, 'b': 2, 'c': 3}


In [7]:
# 딕셔너리 생성4 : (key, value) 쌍으로 된 리스트 사용
dct = dict([('x', 100), ('y', 200)])
print(dct)

{'x': 100, 'y': 200}


In [8]:
# 딕셔너리 생성5: zip() 함수 사용
keys = ['name', 'age', 'city']
values = ['Alice', 28, 'Jeonju']
dct = dict(zip(keys, values))
print(dct)

{'name': 'Alice', 'age': 28, 'city': 'Jeonju'}


In [12]:
# 딕셔너리 생성6: enumerate() 함수 사용
fruits = ['apple', 'banana', 'cherry']
dct = dict(enumerate(fruits))
print(dct)

{0: 'apple', 1: 'banana', 2: 'cherry'}


In [10]:
# 키를 이용한 접근
info = {'name': 'Alice', 'age': 28, 'city': 'Jeonju'}
print(info['name'])
print(info['age'])

Alice
28


In [11]:
# 딕셔너리는 가변형 객체이므로 키를 이용한 수정이 가능함
info = {'name': 'Alice', 'age': 28, 'city': 'Jeonju'}
info['city'] = 'Iksan'
print(info)

{'name': 'Alice', 'age': 28, 'city': 'Iksan'}


In [14]:
# 새로운 키-값 쌍 추가
info['email'] = 'alice123@gmail.com'
print(info)

{'name': 'Alice', 'age': 28, 'city': 'Iksan', 'email': 'alice123@gmail.com'}


### 3.5.2. 딕셔너리 값 접근

In [16]:
# 모든 키 확인
info = {'name': 'Alice', 'age': 28, 'city': 'Jeonju'}
list(info.keys())

['name', 'age', 'city']

In [17]:
# 모든 값 확인
list(info.values())

['Alice', 28, 'Jeonju']

In [18]:
# (키, 값)쌍
list(info.items())

[('name', 'Alice'), ('age', 28), ('city', 'Jeonju')]

In [22]:
# 키를 이용한 값 조회
print(info.get('name'))
print(info.get('hobby'))

Alice
None


In [25]:
# 특정 키 찾기
print('age' in info)
print('hobby' in info)
print(28 in info)        # 키를 확인하는 거라 false로 나옴

True
False
False


#### 3.5.3.2. 딕셔너리 추가/삭제

In [27]:
# 원소 추가 및 수정1
info = {'name': 'Alice', 'age': 28}
info.update({'age': 29, 'city': 'Jeonju'})
print(info)

{'name': 'Alice', 'age': 29, 'city': 'Jeonju'}


In [29]:
# 원소 추가 및 수정2
info = {'name': 'Alice', 'age': 28}
info.update(age=29, city='Jeonju')
print(info)

{'name': 'Alice', 'age': 29, 'city': 'Jeonju'}


In [30]:
# 특정 키의 값 삭제1
info = {'name': 'Alice', 'age': 28, 'city': 'Jeonju'}
age = info.pop('age')
print(info)
print(age)

{'name': 'Alice', 'city': 'Jeonju'}
28


In [32]:
# info.pop('email')
# 오류 발생! 키에러

In [33]:
# 마지막 (키, 값) 쌍 삭제
info = {'name': 'Alice', 'age': 28, 'city': 'Jeonju'}
last_item = info.popitem()
print(info)
print(last_item)

{'name': 'Alice', 'age': 28}
('city', 'Jeonju')


In [35]:
# 특정 키의 원소 삭제1
info = {'name': 'Alice', 'age': 28, 'city': 'Jeonju'}
del info['age']
print(info)

{'name': 'Alice', 'city': 'Jeonju'}


In [38]:
# 특정 키의 원소 삭제2
# del info['hobby']

### 3.5.4. 딕셔너리 패킹과 언패킹
#### 3.5.4.1. 패킹과 언패킹의 개념

In [41]:
# 키워드 가변 인수와 패킹, 언패킹
def print_info(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")
        
info = {'name': 'Alice', 'age': 28, 'city': 'Jeonju'}
print_info(**info)           # 딕셔너리를 언패킹해서 함수에 전달

name: Alice
age: 28
city: Jeonju


### 3.5.5. 딕셔너리 컴프리헨션

In [46]:
# 문자 개수 세기
word = "Hello"
[char for char in word]
[word.count(char) for char in word]

{char: word.count(char) for char in word}

{'H': 1, 'e': 1, 'l': 2, 'o': 1}

In [49]:
# 두 리스트를 키와 값으로 합치기
keys = ['name', 'age', 'city']
values = ['Alice', 28, 'Jeonju']
info = {k: v for k, v in zip(keys, values)}
print(info)

{'name': 'Alice', 'age': 28, 'city': 'Jeonju'}


In [51]:
# 리스트를 인덱스와 함께 딕셔너리로 변환
fruits = ['apple', 'banana', 'cherry']
dct = {i: fruit for i, fruit in enumerate(fruits)}
print(dct)

{0: 'apple', 1: 'banana', 2: 'cherry'}


In [54]:
scores = {'Alice': 85, 'Bob': 92, 'Chalie': 77, 'David': 90}
{name: score for name, score in scores.items() if score >= 80}

{'Alice': 85, 'Bob': 92, 'David': 90}

In [59]:
# 가격(값)에 5%의 할인 적용
prices = {'apple': 1000, 'banana': 800, 'cherry': 1500}
{item: price*0.95 for item, price in prices.items()}

{'apple': 950.0, 'banana': 760.0, 'cherry': 1425.0}

# 4. 라이브러리
## 4.1. Numpy 라이브러리
### 4.1.1. 넘파이 배열
#### 4.1.1.2. 넘파이 배열 생성

In [63]:
# 넘파이 설치 !pip install numpy

In [64]:
import numpy as np

In [65]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [70]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [72]:
arr = np.ones(3)
print(arr)
print(type(arr))

[1. 1. 1.]
<class 'numpy.ndarray'>


In [73]:
#arr = np.full(내가 채울 값, 몇 개 원소)
arr = np.full(2, 5)
print(arr)

[5 5]


In [75]:
list(range(1, 11, 2))     # 실수는 안됨! 1.5 XX 정수만 가능

[1, 3, 5, 7, 9]

In [79]:
arr = np.arange(0.5, 11.5, 1)
print(arr)                         # 실수도 된다

[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5]


In [80]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [84]:
arr = np.eye(3, 4, k=1)        # 행과 열의 개수 지정 가능
print(arr)                     # k를 이용해서 1 어디서 시작할지 바꿀 수 O

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [82]:
arr - np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
